CREATE TABLE contact_type (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
type VARCHAR NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE user_profile (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
role VARCHAR,
email VARCHAR NOT NULL,
first_name VARCHAR NOT NULL,
last_name VARCHAR NOT NULL,
password VARCHAR NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE contact (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
first_name VARCHAR,
last_name VARCHAR,
address VARCHAR,
phone_number VARCHAR,
contact_type_id BIGINT,
user_profile_id BIGINT,
PRIMARY KEY (id),
FOREIGN KEY (contact_type_id) REFERENCES contact_type (id),
FOREIGN KEY (user_profile_id) REFERENCES user_profile (id)
);

